// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    executive_summary: {
        name: "executive_summary";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType DECIMAL(14,1) */
          peak_demand_mw: number;
          /** @sqlType DECIMAL(8,1) */
          avg_utilization_pct: number;
          /** @sqlType BIGINT */
          outage_count: number;
          /** @sqlType BIGINT */
          customers_affected: number;
          /** @sqlType DECIMAL(26,0) */
          financial_impact_usd: number;
          /** @sqlType DECIMAL(6,1) */
          reliability_score: number;
        }>;
      };
    feeder_risk: {
        name: "feeder_risk";
        parameters: Record<string, never>;
        result: Array<{
          /** Stable identifier for a feeder, transformer, or substation */
          asset_id: string;
          /** Excel Energy operating region responsible for the asset */
          service_region: string;
          /** Business criticality tier assigned by grid operations */
          criticality: string;
          /** @sqlType DECIMAL(8,1) */
          peak_utilization_pct: number;
          /** Number of outage events linked to the asset */
          outage_count: number;
          /** @sqlType DECIMAL(15,0) */
          financial_impact_usd: number;
          /** @sqlType DECIMAL(6,1) */
          risk_score: number;
          /** Executive risk category derived from risk score: Critical, High, Moderate, or Low */
          risk_band: string;
          /** Plain-English operational recommendation associated with the asset risk level */
          recommended_action: string;
        }>;
      };
    outage_causes: {
        name: "outage_causes";
        parameters: Record<string, never>;
        result: Array<{
          /** Primary operational cause assigned by the outage-management system */
          cause: string;
          /** @sqlType BIGINT */
          outage_count: number;
          /** @sqlType BIGINT */
          customers_affected: number;
          /** @sqlType DECIMAL(25,0) */
          financial_impact_usd: number;
        }>;
      };
    regional_impact: {
        name: "regional_impact";
        parameters: Record<string, never>;
        result: Array<{
          /** Excel Energy operating region used for geographic comparisons and filters */
          service_region: string;
          /** @sqlType BIGINT */
          customers_affected: number;
          /** @sqlType DECIMAL(26,0) */
          financial_impact_usd: number;
          /** @sqlType DECIMAL(6,1) */
          reliability_score: number;
        }>;
      };
  }
}
